/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:3a9897a7-e508-40d1-8fa4-e0294ebb47ac",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_E0XOH61iP",
    "aws_user_pools_web_client_id": "jugfnge6ghiri1jts9jtbcehl",
    "oauth": {}
};


export default awsmobile;
